### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by cramhead** [kalcifer/webpack-library-example#2]
I just wanted to say thanks for making this project. 
I used it as a starting point for learning how to make one with TypeScript.
Just in case you are curious https://github.com/cramhead/webpack-library-example

Marc

**Comment by rockchalkwushock** [comment]
Thanks so much for this I was lost in how to webpack for building a library this is great!

**Comment by pksjce** [comment]
Hey thanks for the appreciation! Really glad this helped you!

**Comment by benmarten** [comment]
Maybe close this after saying thx? This is not an issue ;)
