### ISSUE TITLE
converttonum

### ISSUE THREAD

**Issue by pustun** [kalcifer/webpack-library-example#6]
Hi guys, it's not actually  an issue, it's a question.

I can't get what is the reason to call **word.toLowerCase()** ? index.js line 24
How does it help here?!

Another small thing.
I understand why you use here lodash, question is why do you use **reduce** ? I'd say it's too sophisticated way to find an element in the collection.
**find** method might be a good option.

Something like this: return **_.find(numRef, ref => ref.word === word)** it will either return the first item of the collection or undefined if such does not exist.

**Comment by rahulcs** [comment]
It's just a contrived use case I believe /cc @pksjce

**Comment by pksjce** [comment]
Yep! It's just a way to use lodash, not really a make or break for the example.
